# Generated by Django 4.2.7 on 2025-11-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_full_name_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('homeowner', 'Homeowner'), ('maid', 'Maid'), ('cleaning_company', 'Cleaning Company'), ('home_nurse', 'Home Nurse'), ('admin', 'Admin')], max_length=20),
        ),
    ]
