# Generated by Django 4.2.7 on 2025-11-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeownerprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='homeowner_documents/ids/'),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='lc_letter',
            field=models.FileField(blank=True, null=True, upload_to='homeowner_documents/lc_letters/'),
        ),
        migrations.AlterField(
            model_name='homeownerprofile',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeownerprofile',
            name='home_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('condo', 'Condominium')], default='apartment', max_length=50),
        ),
        migrations.AlterField(
            model_name='homeownerprofile',
            name='preferred_maid_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10, null=True),
        ),
    ]
