# Generated by Django 4.2.7 on 2025-11-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0002_homeownerprofile_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeownerprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Account active status. Can be deactivated by admin if needed.'),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Account verified by admin'),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes on verification status', null=True),
        ),
        migrations.AlterField(
            model_name='homeownerprofile',
            name='id_document',
            field=models.FileField(blank=True, help_text='Upload a copy of government-issued ID', null=True, upload_to='homeowner_documents/ids/'),
        ),
        migrations.AlterField(
            model_name='homeownerprofile',
            name='lc_letter',
            field=models.FileField(blank=True, help_text='Letter of recommendation or LC letter (if applicable)', null=True, upload_to='homeowner_documents/lc_letters/'),
        ),
    ]
