# Generated by Django 4.2.7 on 2025-11-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0003_homeownerprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='homeowner.job'),
        ),
    ]
