# Generated by Django 4.2.7 on 2025-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0004_alter_review_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='communication',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Communication/Respect', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='punctuality',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='quality',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Cleanliness/Work Quality', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reliability',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
