# Generated by Django 4.2.7 on 2025-11-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0004_maidprofile_category'),
        ('homeowner', '0005_review_communication_review_punctuality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_jobs', to='homeowner.homeownerprofile')),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_jobs', to='maid.maidprofile')),
            ],
            options={
                'db_table': 'closed_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
