# Generated by Django 4.2.7 on 2025-11-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0006_closedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fairness_workload',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='payment_timeliness',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='respect_communication',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='safety_environment',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
