# Generated by Django 4.2.7 on 2025-11-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_nursing', '0007_homenurse_gender'),
        ('cleaning_company', '0010_cleaningcompany_service_pricing'),
        ('maid', '0007_alter_maidprofile_category'),
        ('homeowner', '0007_review_fairness_workload_review_payment_timeliness_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cleaning_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='cleaning_company.cleaningcompany'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='home_nursing.homenurse'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='maid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='maid.maidprofile'),
        ),
    ]
