# Generated by Django 4.2.7 on 2025-12-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0009_homeownerprofile_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeownerprofile',
            name='has_live_in_credit',
            field=models.BooleanField(default=False, help_text='Whether homeowner has an unused paid live-in placement credit (Plan A)'),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='live_in_credit_awarded_at',
            field=models.DateTimeField(blank=True, help_text='When the current live-in credit was last purchased', null=True),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the current subscription (monthly/day pass) expires', null=True),
        ),
        migrations.AddField(
            model_name='homeownerprofile',
            name='subscription_type',
            field=models.CharField(choices=[('none', 'No active subscription'), ('monthly', 'Monthly subscription'), ('day_pass', '24 hour pass')], default='none', help_text='Current homeowner subscription plan type (Plan B/C)', max_length=20),
        ),
    ]
