# Generated by Django 4.2.7 on 2025-11-25 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0002_seed_service_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cleaning_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cleaning_company.cleaningcompany')),
            ],
            options={
                'verbose_name': 'Cleaning Work Image',
                'verbose_name_plural': 'Cleaning Work Gallery',
                'ordering': ['-created_at'],
            },
        ),
    ]
