# Generated by Django 4.2.7 on 2025-11-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0004_cleaningcompany_display_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningcompany',
            name='display_photo',
        ),
    ]
