# Generated by Django 4.2.7 on 2025-11-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0005_remove_cleaningcompany_display_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningcompany',
            name='display_photo',
            field=models.ImageField(blank=True, null=True, upload_to='company_photos/'),
        ),
    ]
