# Generated by Django 4.2.7 on 2025-11-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0008_alter_servicecategory_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='group',
            field=models.CharField(choices=[('house', 'House Cleaning Services'), ('external', 'External / Compound Services'), ('fumigation', 'Fumigation / Pest Control'), ('commercial', 'Commercial / Office Cleaning'), ('laundry', 'Laundry Services')], max_length=20),
        ),
    ]
