# Generated by Django 4.2.7 on 2025-11-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0009_alter_servicecategory_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningcompany',
            name='service_pricing',
            field=models.TextField(blank=True, help_text='Per-service starting pay in free text (one per line)', null=True),
        ),
    ]
