# Generated by Django 4.2.7 on 2025-12-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0011_cleaningcompany_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningcompany',
            name='has_active_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleaningcompany',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaningcompany',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=20, null=True),
        ),
    ]
