# Generated by Django 4.2.7 on 2025-12-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0012_cleaningcompany_has_active_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningcompany',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='If true, company is taking a break and will not see/receive jobs.'),
        ),
    ]
