# Generated by Django 4.2.7 on 2025-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0013_cleaningcompany_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningcompany',
            name='id_document',
            field=models.FileField(blank=True, help_text='Business registration certificate or owner ID document', null=True, upload_to='company_documents/'),
        ),
    ]
