# Generated by Django 4.2.7 on 2025-11-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills', null=True)),
                ('availability_status', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='maid_documents/ids/')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='maid_documents/certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maid_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maid Profile',
                'verbose_name_plural': 'Maid Profiles',
                'db_table': 'maid_profiles',
            },
        ),
        migrations.CreateModel(
            name='MaidAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='maid.maidprofile')),
            ],
            options={
                'verbose_name': 'Maid Availability',
                'verbose_name_plural': 'Maid Availabilities',
                'db_table': 'maid_availability',
                'unique_together': {('maid', 'day_of_week')},
            },
        ),
    ]
