# Generated by Django 4.2.7 on 2025-11-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Current location (auto-detected or manual)', max_length=255),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='maid_profiles/photos/'),
        ),
    ]
