# Generated by Django 4.2.7 on 2025-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0002_maidprofile_date_of_birth_maidprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Account enabled/disabled by admin'),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Account verified by admin'),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes on verification', null=True),
        ),
    ]
