# Generated by Django 4.2.7 on 2025-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0003_maidprofile_is_enabled_maidprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('temporary', 'Temporary'), ('live_in', 'Live-in')], max_length=20, null=True),
        ),
    ]
