# Generated by Django 4.2.7 on 2025-11-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0004_maidprofile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaidServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('group', models.CharField(choices=[('domestic_housekeeping', 'Domestic Housekeeping Services'), ('nanny_childcare', 'Nanny / Childcare Services'), ('elderly_support', 'Home Care & Elderly Support'), ('residential_cleaning', 'Residential Cleaning Services'), ('live_in_maid', 'Live-in Maid Services'), ('live_out_maid', 'Live-out Maid Services'), ('cooking_meals', 'Cooking & Meal Preparation'), ('laundry_ironing', 'Laundry & Ironing Services'), ('placement_recruitment', 'Domestic Staff Placement / Recruitment'), ('home_assistant', 'Home Assistant Services'), ('after_party_cleaning', 'After-Party & Event Cleaning Services'), ('event_helpers', 'Cooking, Serving & Event Helpers')], max_length=40)),
            ],
            options={
                'verbose_name': 'Maid Service Category',
                'verbose_name_plural': 'Maid Service Categories',
            },
        ),
    ]
