# Generated by Django 4.2.7 on 2025-11-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0005_maidservicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='service_pricing',
            field=models.TextField(blank=True, help_text='Per-service starting pay in free text (one per line)', null=True),
        ),
    ]
