# Generated by Django 4.2.7 on 2025-11-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0006_maidprofile_service_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maidprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('temporary', 'Temporary'), ('live_in', 'Live-in'), ('placement', 'Domestic Staff Placement')], max_length=20, null=True),
        ),
    ]
