# Generated by Django 4.2.7 on 2025-11-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0007_alter_maidprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='maidprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Home/base latitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='maidprofile',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Home/base location (manual or approximate)', max_length=255),
        ),
        migrations.AlterField(
            model_name='maidprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Home/base longitude', max_digits=9, null=True),
        ),
    ]
