# Generated by Django 4.2.7 on 2025-12-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0008_maidprofile_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidprofile',
            name='onboarding_fee_paid',
            field=models.BooleanField(default=False, help_text='Whether the maid has paid the onboarding fee'),
        ),
        migrations.AddField(
            model_name='maidprofile',
            name='onboarding_fee_paid_at',
            field=models.DateTimeField(blank=True, help_text='When the onboarding fee was recorded as paid', null=True),
        ),
    ]
