# Generated by Django 4.2.7 on 2025-11-25 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Nursing Service Category',
                'verbose_name_plural': 'Nursing Service Categories',
            },
        ),
        migrations.CreateModel(
            name='HomeNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nursing_level', models.CharField(choices=[('enrolled', 'Enrolled Nurse'), ('registered', 'Registered Nurse'), ('midwife', 'Midwife')], max_length=20)),
                ('council_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('preferred_working_hours', models.CharField(blank=True, help_text='e.g., Weekdays 8am-5pm or Nights', max_length=120)),
                ('emergency_availability', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(blank=True, related_name='nurses', to='home_nursing.nursingservicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_nurse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home Nurse',
                'verbose_name_plural': 'Home Nurses',
                'db_table': 'home_nurses',
            },
        ),
    ]
