# Generated by Django 4.2.7 on 2025-11-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_nursing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursingservicecategory',
            name='group',
            field=models.CharField(choices=[('elderly', 'Elderly Care'), ('post_surgery', 'Post-Surgery Care'), ('special_needs', 'Special Needs Care'), ('baby_infant', 'Baby & Infant Care'), ('palliative', 'Palliative Care (End-of-life)'), ('home_medical', 'Home Medical Support')], default='Elderly Care', max_length=20),
            preserve_default=False,
        ),
    ]
