# Generated by Django 4.2.7 on 2025-11-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_nursing', '0002_nursingservicecategory_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='homenurse',
            name='display_photo',
            field=models.ImageField(blank=True, null=True, upload_to='nurse/display/'),
        ),
    ]
