# Generated by Django 4.2.7 on 2025-11-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_nursing', '0003_homenurse_display_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homenurse',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
