# Generated by Django 4.2.7 on 2025-11-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_nursing', '0005_homenurse_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='homenurse',
            name='service_pricing',
            field=models.TextField(blank=True, help_text='Per-category starting pay in free text (one per line)', null=True),
        ),
    ]
