# Generated by Django 4.2.7 on 2025-11-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_nursing', '0006_homenurse_service_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='homenurse',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
