# Generated by Django 4.2.7 on 2025-11-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_nursing', '0007_homenurse_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='homenurse',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='homenurse',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='homenurse',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='homenurse',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
