# Generated by Django 4.2.7 on 2025-12-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_nursing', '0008_homenurse_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homenurse',
            name='id_document',
            field=models.FileField(blank=True, help_text='Upload a copy of government-issued ID', null=True, upload_to='nurse_documents/ids/'),
        ),
        migrations.AddField(
            model_name='homenurse',
            name='nursing_certificate',
            field=models.FileField(blank=True, help_text='Upload proof of nursing qualification (certificate or diploma)', null=True, upload_to='nurse_documents/certificates/'),
        ),
    ]
