# Generated by Django 4.2.7 on 2025-12-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_nursing', '0009_homenurse_id_document_homenurse_nursing_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='homenurse',
            name='onboarding_fee_paid',
            field=models.BooleanField(default=False, help_text='Whether the nurse has paid the onboarding fee'),
        ),
        migrations.AddField(
            model_name='homenurse',
            name='onboarding_fee_paid_at',
            field=models.DateTimeField(blank=True, help_text='When the onboarding fee was recorded as paid', null=True),
        ),
    ]
