# Generated by Django 4.2.7 on 2025-12-09 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0009_homeownerprofile_current_latitude_and_more'),
        ('maid', '0009_maidprofile_onboarding_fee_paid_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='homeowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='homeowner.homeownerprofile'),
        ),
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='purpose',
            field=models.CharField(choices=[('maid_onboarding', 'Maid onboarding fee'), ('homeowner_live_in', 'Homeowner live-in placement fee'), ('homeowner_monthly', 'Homeowner monthly subscription'), ('homeowner_day_pass', 'Homeowner 24h access pass')], default='maid_onboarding', max_length=50),
        ),
        migrations.AlterField(
            model_name='mobilemoneytransaction',
            name='maid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='maid.maidprofile'),
        ),
    ]
