# Generated by Django 4.2.7 on 2025-12-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_company', '0012_cleaningcompany_has_active_subscription_and_more'),
        ('payments', '0002_mobilemoneytransaction_homeowner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cleaning_company.cleaningcompany'),
        ),
        migrations.AlterField(
            model_name='mobilemoneytransaction',
            name='purpose',
            field=models.CharField(choices=[('maid_onboarding', 'Maid onboarding fee'), ('homeowner_live_in', 'Homeowner live-in placement fee'), ('homeowner_monthly', 'Homeowner monthly subscription'), ('homeowner_day_pass', 'Homeowner 24h access pass'), ('company_monthly', 'Cleaning company monthly plan'), ('company_annual', 'Cleaning company annual plan')], default='maid_onboarding', max_length=50),
        ),
    ]
