# Generated by Django 4.2.7 on 2025-12-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_nursing', '0010_homenurse_onboarding_fee_paid_and_more'),
        ('payments', '0003_mobilemoneytransaction_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='home_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home_nursing.homenurse'),
        ),
        migrations.AlterField(
            model_name='mobilemoneytransaction',
            name='purpose',
            field=models.CharField(choices=[('maid_onboarding', 'Maid onboarding fee'), ('home_nurse_onboarding', 'Home nurse premium onboarding fee'), ('homeowner_live_in', 'Homeowner live-in placement fee'), ('homeowner_monthly', 'Homeowner monthly subscription'), ('homeowner_day_pass', 'Homeowner 24h access pass'), ('company_monthly', 'Cleaning company monthly plan'), ('company_annual', 'Cleaning company annual plan')], default='maid_onboarding', max_length=50),
        ),
    ]
